import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildInspectionExportData } from '../js/xlsx.js';
import { availableRowLines, sliceRowLineSets } from '../js/report.js';
import { hydrateDocument, RESULT } from '../js/domain.js';

const duplicateSource = hydrateDocument({ id:'d1', code:'PW-1', description:'NC', expectedRevision:'A', fieldCopies:[{ id:'c1', foundRevision:'B', sequence:1, confirmed:true }] });
const inspection = { id:'inspection-1', name:'Teste', project:'P', system:'S', responsible:'R', location:'L', documents:[duplicateSource, structuredClone(duplicateSource), hydrateDocument({ id:'d2', code:'PW-2', description:'NF', expectedRevision:'A', result:RESULT.NOT_FOUND, fieldCopies:[] }), hydrateDocument({ id:'d3', code:'PW-3', description:'Pendente', expectedRevision:'A', result:RESULT.PENDING, fieldCopies:[] })] };
const data = buildInspectionExportData(inspection, { includeConforming:false, includeNonconforming:true, includeNotFound:true, includePending:false, includeCopies:true });
assert.deepEqual(data.documents.map(row => row['Código PW']), ['PW-1','PW-2']);
assert.equal(data.documents.length, 2);
assert.equal(data.copies.length, 1);
assert.equal(data.metrics.total, 2);
assert.equal(data.metrics.verified, 2);
assert.equal(data.metrics.pending, 0);

const app = fs.readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
const report = fs.readFileSync(new URL('../js/report.js', import.meta.url), 'utf8');
const word = fs.readFileSync(new URL('../js/word.js', import.meta.url), 'utf8');
const serviceWorker = fs.readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const authEntry = fs.readFileSync(new URL('../js/auth-entry.js', import.meta.url), 'utf8');
const visualSystem = fs.readFileSync(new URL('../visual-system.css', import.meta.url), 'utf8');
const visualVerify = fs.readFileSync(new URL('../visual-verify.css', import.meta.url), 'utf8');
const visualDocuments = fs.readFileSync(new URL('../visual-documents.css', import.meta.url), 'utf8');
const visualOverlays = fs.readFileSync(new URL('../visual-overlays.css', import.meta.url), 'utf8');
const visualResponsive = fs.readFileSync(new URL('../visual-responsive.css', import.meta.url), 'utf8');
const markingPolicy = fs.readFileSync(new URL('../js/marking-policy-ui.js', import.meta.url), 'utf8');
const copyEvidenceEdit = fs.readFileSync(new URL('../js/copy-evidence-edit-ui.js', import.meta.url), 'utf8');

assert.match(app, /id="copy-quantity"/);
assert.match(app, /if \(!input \|\| input\.dataset\.bound\) return;[\s\S]{0,80}input\.dataset\.bound = '1';/);
assert.match(app, /data-copy-edit=/);
assert.match(app, /id="next-document"/);
assert.match(app, /id="clear-pw-search"/);
assert.match(app, /Registrar por foto/);
assert.match(app, /documents-dashboard/);
const inspectViewSource = app.match(/function inspectView\(\)[\s\S]*?function normalizeSearchText/);
assert.ok(inspectViewSource);
assert.doesNotMatch(inspectViewSource[0], /global-dashboard/);
assert.doesNotMatch(app, /querySelector\('#global-dashboard'\)/);
assert.doesNotMatch(report, /boundedLines/);
assert.doesNotMatch(report, /maxLines:/);
const lineSets = [['a1','a2','a3','a4','a5'], ['b1','b2'], ['c1','c2','c3']];
const firstChunk = sliceRowLineSets(lineSets, [0,0,0], 2);
assert.deepEqual(firstChunk.chunkSets, [['a1','a2'], ['b1','b2'], ['c1','c2']]);
assert.deepEqual(firstChunk.nextOffsets, [2,2,2]);
assert.equal(firstChunk.done, false);
const secondChunk = sliceRowLineSets(lineSets, firstChunk.nextOffsets, 2);
assert.deepEqual(secondChunk.chunkSets, [['a3','a4'], [], ['c3']]);
assert.equal(secondChunk.done, false);
const thirdChunk = sliceRowLineSets(lineSets, secondChunk.nextOffsets, 2);
assert.deepEqual(thirdChunk.chunkSets, [['a5'], [], []]);
assert.equal(thirdChunk.done, true);
assert.equal(availableRowLines(5.6), 0);
assert.equal(availableRowLines(6.99), 0);
assert.equal(availableRowLines(7), 1);

assert.match(serviceWorker, /const VERSION = '0\.9\.30';/);
for (const asset of ['visual-system.css','visual-verify.css','visual-documents.css','visual-overlays.css','visual-responsive.css','visual-refinement.css','js/marking-policy-ui.js','js/copy-evidence-edit-ui.js','js/ui-refinement.js']) {
  assert.ok(serviceWorker.includes(`./${asset}`), `${asset} deve estar no shell offline`);
}
for (const asset of ['visual-system.css','visual-verify.css','visual-documents.css','visual-overlays.css','visual-responsive.css']) assert.ok(index.includes(`href="${asset}"`));
assert.ok(index.includes('href="visual-refinement.css"'));
assert.match(authEntry, /import\('\.\/marking-policy-ui\.js'\)/);
assert.match(authEntry, /import\('\.\/copy-evidence-edit-ui\.js'\)/);
assert.match(authEntry, /import\('\.\/ui-refinement\.js'\)/);
assert.match(markingPolicy, /new Set\(\['Amarelo', 'Vermelho'\]\)/);
assert.match(markingPolicy, /input\.checked = false;[\s\S]*input\.disabled = true;/);
assert.match(copyEvidenceEdit, /context\.copy\.evidenceId = evidenceId/);
assert.doesNotMatch(copyEvidenceEdit, /addFieldCopy\(/);
assert.match(visualVerify, /white-space: normal;[\s\S]*overflow-wrap: anywhere;/);
assert.match(visualDocuments, /table-layout: fixed/);
assert.match(visualDocuments, /-webkit-line-clamp: 3/);
assert.match(visualOverlays, /copy-evidence-edit-field/);
assert.match(visualOverlays, /border-radius: var\(--radius-modal-v2\) var\(--radius-modal-v2\) 0 0/);
assert.match(visualResponsive, /body \{ min-width: 320px; \}/);
assert.match(visualResponsive, /body\.keyboard-open \.mobile-nav/);
assert.match(visualResponsive, /@media \(max-width: 350px\)/);
assert.match(visualResponsive, /env\(safe-area-inset-bottom\)/);
assert.match(visualSystem, /--color-navy-900:/);
assert.match(visualSystem, /--control-height-v2: 48px/);
assert.match(word, /application\/msword/);
console.log('feature-export-verification-documents.test.mjs: OK');
